@host=https://localhost:7288
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YjZiZWU1My1jYWM4LTQyNTAtODk2My1iMWMxNTNlNjNmZWMiLCJnaXZlbl9uYW1lIjoiQ2hhdGh1cmEiLCJmYW1pbHlfbmFtZSI6IkxpeWFuYWdlIiwianRpIjoiMTFlY2M5ZGQtNmY1OC00NGQ3LThlOTUtN2YwYzYwYTAzY2M0IiwiZXhwIjoxNzIwOTcyOTc0LCJpc3MiOiJDakRpbm5lciIsImF1ZCI6IkNqRGlubmVyIn0.7kEVOLshxoRvvSIZPE9SC3SG2nCrcmua_CPMW8SgOzY
@hostId=asdr
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 0,
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}