@host=https://localhost:7288
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MGNlNTNjMi1mMmFhLTQyNmUtYjM5MS04OTFhZDA0N2QxNjMiLCJnaXZlbl9uYW1lIjoiQ2hhdGh1cmEiLCJmYW1pbHlfbmFtZSI6IkxpeWFuYWdlIiwianRpIjoiMzBlZjRiMjQtYWRhMC00MWM5LWE3NTItY2JhNjIzMGJiNmY0IiwiZXhwIjoxNzIxMzM2MjkzLCJpc3MiOiJDakRpbm5lciIsImF1ZCI6IkNqRGlubmVyIn0.IEQoJXT50tYZBzuVfPCB6eD7C-gHwBZatWdL7eW9jm4
@hostId=asdrr
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu 3",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}