GET https://localhost:7288/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E2ZjQyYi1iNTk2LTQ0N2EtOGJkZS1hYTUxYjI0YTdmMzUiLCJnaXZlbl9uYW1lIjoiQ2hhdGh1cmEiLCJmYW1pbHlfbmFtZSI6IkxpeWFuYWdlIiwianRpIjoiODczNDM0MjAtZmZmZi00NWVlLWE2OWEtYTQzYmY5YTQwZjk0IiwiZXhwIjoxNzE5ODcwMTgyLCJpc3MiOiJDakRpbm5lciIsImF1ZCI6IkNqRGlubmVyIn0.TYEDUqMQaebBRiQevpJEBZYFK7l4Yt_W5bAgHsKB7uw